### ISSUE TITLE
db level features?

### ISSUE THREAD

**Issue by cdaringe** [cliffano/couchtato#11]
hello:
couchtato looks neat.  i want to, say, delete all my databases!  Sounds crazy.  Are there DB level opts vs doc level?
thx,
chris

**Comment by cliffano** [comment]
@cdaringe 
couchtato doesn't currently have any db-level concept.

However, if your goal is to delete all databases, it can easily be done by using Couchpenter's teardown-db command (https://github.com/cliffano/couchpenter)

Steps:
1. Create a Couchpenter config file that contains all databases
    You can run this script (https://gist.github.com/cliffano/71d0f655e5181e5f63a2) to automatically generate couchpenter.json config file from a CouchDB database URL
2. Use Couchpenter couchpenter teardown-db -u http://user:pass@couchdb_host:port

Let me know how you go.

**Comment by cdaringe** [comment]
thanks! i ended up generating my own CLI tool to achieve my needs. thanks for the response tho
