### ISSUE TITLE
Multi-pages removes (>1000docs) are ineffective

### ISSUE THREAD

**Issue by ronjouch** [cliffano/couchtato#13]
**Steps to reproduce**

* Make a rule file that will run a `util.remove(doc)` for more than one page (i.e. 1000 documents, if I understand correctly)
* Run

**Expected**

Documents are removed

**Actual**

Documents are not removed, each successive run prints the same amount "removed":

```
[2016-03-16 13:57:31.765] [INFO] [default] - 
------------------------
Retrieved 1161 documents in 2 pages
Processed 0 saves and 1100 removes
```
But looking at futon, the documents were *not* removed. And indeed, re-trying the same command, they still appear and are still not deleted:
```
[2016-03-16 13:57:47.698] [INFO] [default] - 
------------------------
Retrieved 1161 documents in 2 pages
Processed 0 saves and 1100 removes
```

Now, if I first delete a batch of ~200, this one is successful:
```
[2016-03-16 13:58:04.639] [INFO] [default] - 
------------------------
Retrieved 1161 documents in 2 pages
Processed 0 saves and 199 removes
```
... and now deleting the rest works too:
```
[2016-03-16 13:58:32.490] [INFO] [default] - 
------------------------
Retrieved 962 documents in 1 pages
Processed 0 saves and 901 removes
```

**Comment by rajasaur** [comment]
I just tried to delete a batch of 3900 documents and it went through fine(Took a bit of time, but it did delete them properly). Log output snippet:

Retrieved 3919 documents in 4 pages
Processed 0 saves and 3919 removes

**Comment by cliffano** [comment]
Sorry I have not been able to reproduce the problem either.

Please try verifying whether the expected requests and parameters were received by CouchDB.
If not, then it could be couchtato issue, otherwise it's something on CouchDB end.

**Comment by ronjouch** [comment]
Understood. Closing, will re-open if I ever stumble upon the problem and can precise a reproduction scenario. Thanks for trying.
