### ISSUE TITLE
How do you deal with async scenarios 

### ISSUE THREAD

**Issue by kevbook** [cliffano/couchtato#14]
For example:
```js
"update-by-criteria": function (util, doc) {
    if (doc.status === 'new') {
        getNewData(function(data) {
            doc.data = data;
            util.save(doc);
        });
    }
}
```

**Comment by cliffano** [comment]
I have not tried this myself, but one user reported to me that she solved it by using deasync module https://www.npmjs.com/package/deasync .

**Comment by cliffano** [comment]
Closing this issue, feel free to re-open if there's any further update.
