### ISSUE TITLE
how to iterate all db

### ISSUE THREAD

**Issue by mrjumpy** [cliffano/couchtato#15]
I have a cloudant account, I want to iterate all db,
not just one db.
How should I do ?
thanks

**Comment by mrjumpy** [comment]
```
#!/bin/bash
output=$(curl –s –u ${1} "https://${1}:${2}@${1}.cloudant.com/_all_dbs");

opt2="${output/[/}";
opt3="${opt2/]/}";

IFS=","
export IFS;


for i in $opt3; 
do 
  temp="${i%\"}";
  temp2="${temp#\"}";
if [ "$temp2" != "_replicator" -a "$temp2" != "_users" ]; then

  echo "${temp2}";
  couchtato iterate -u https://${1}:${2}@${1}.cloudant.com/${temp2} -c /db/migrate/migrate.js
fi
done
```

then `./script.sh db_account db_password 

my first time to write script.

**Comment by cliffano** [comment]
Thanks @mrjumpy for adding the shell script.
If anyone needs a node script, check out https://gist.github.com/cliffano/71d0f655e5181e5f63a2 , simply replace the bit that creates couchpenter.js with your own action (i.e. calling `couchtato iterate`).
