### ISSUE TITLE
Still accepting PRs?

### ISSUE THREAD

**Issue by dsquier** [cliffano/couchtato#16]
Appreciate your work on this library. It's been helpful.

Are you still maintaining couchtato (i.e., accepting PRs)?

- If so, I've added some new features (maintaining backward compatibility) I'd like to submit.
- If not, would you be interested in allowing other maintainers?

Thanks much!

**Comment by cliffano** [comment]
@dsquier Happy to accept PRs, please feel free to create them.

**Comment by dsquier** [comment]
@cliffano Here's the PR: https://github.com/cliffano/couchtato/pull/17

Some additional thoughts:

1) I am using `couchtato` in AWS Lambda functions, which surfaced an issue with logging..
    - Changes to the logger were needed to remove the file-based loadAppender options, otherwise the lambda will fail when couchtato attempts to open a file handle to the `couchtato.txt` log file. This is true even if `opts.quiet === true`.
    - My original PR removed `log4js` and switched `Util.log()` to console.log. This solved my problem but wasn't very clean or extensible, so I reverted it. 
    - I'd like to solve this so the library can be used in both contexts (CLI and lambda) without code changes.

2) I made every attempt to maintain backwards compatibility. I've tested these changes in both CLI and lambda contexts and have been running the version without `log4js` in production for the past week.

3) Added instructions and related scripts/config files to perform local testing. Apologies if this already existed, I don't have much experience with `buster` testing and had to do this to run the tests locally anyway.

4) Finally, in addition to changes from #1 I had a few more lower-priority changes I'd like to eventually make, namely:

    - Remove the need for `lodash`. There are two lodash functions used, `keys()` and `isEmpty()` and my understanding is we can replace `_.keys()` with `Object.keys()`, which is faster from the benchmarks I've seen (https://jsperf.com/lodash-keys-vs-object-keys).
    - Add util function to enable JSON schema validation (likely via `ajv` module)
    - Expose more config parameters, and ideally have a config parameter for issues related to #1 above.

**Comment by cliffano** [comment]
To preserve backward compatibility and yet to allow scenario like Lambda, I think a reasonable solution is to provide new CLI flag, e.g. `--log-output file,console` . If not specified, it should default to `file,console` which will do what it's doing now, i.e. add the file appender on top of default console output. This should satisfy current users.

For Lambda scenario, you can set `--log-output console` which shouldn't add the file appender.

The flag values should be available as opt at `Couchtato.prototype.iterate`, it can then be passed to `Util`'s constructor.

**Comment by cliffano** [comment]
@dsquier Thanks for PR #17 , merged and will be included in v0.3.0 .

Would you be able to raise another PR for the `--log-output` scenario above?

**Comment by cliffano** [comment]
Closing this ticket due to lack of update.
Happy to accept PR covering `--log-output` scenario.
